### ISSUE TITLE
Instantly connecting to the server when starting (Usually by bot) causes the server to error out

### ISSUE THREAD

**Issue by wolfy01** [BopItFreak/mpp-server#10] opened 2020-01-16 23:28 UTC
I turned on my bridge bot.. Which I thought was causing the issue with an instant connection to the server on startup (Turned out to be true).
Then I started the server while my bot was running, and this caused the error

Here is the error log
```
CONNECTED IP: my.bot.xxx.ip
TypeError: Cannot set property 'id' of undefined
at Room.join (/app/src/Room.js:37:18)
at Client.setChannel (/app/src/Client.js:59:26)
at Client.cl.on.msg (/app/src/Message.js:29:16)
    at Client.emit (events.js:189:13)
at WebSocket.ws.on (/app/src/Client.js:89:26)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/rbd/pnpm-volume/72a24911-4d49-4ea5-aa93-31d2f107df86/node_modules/.registry.npmjs.org/ws/7.2.1/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (/rbd/pnpm-volume/72a24911-4d49-4ea5-aa93-31d2f107df86/node_modules/.registry.npmjs.org/ws/7.2.1/node_modules/ws/lib/receiver.js:423:14)
    at Receiver.getData (/rbd/pnpm-volume/72a24911-4d49-4ea5-aa93-31d2f107df86/node_modules/.registry.npmjs.org/ws/7.2.1/node_modules/ws/lib/receiver.js:353:17)
/app/src/Room.js:101
      console.log(`Deleted client ${p.user.id}`);
                                           ^
TypeError: Cannot read property 'id' of undefined
at Room.remove (/app/src/Room.js:101:44)
at Room.on.participant (/app/src/Room.js:452:12)
    at Room.emit (events.js:189:13)
at Client.destroy (/app/src/Client.js:71:26)
at WebSocket.ws.on (/app/src/Client.js:94:22)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/rbd/pnpm-volume/72a24911-4d49-4ea5-aa93-31d2f107df86/node_modules/.registry.npmjs.org/ws/7.2.1/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (/rbd/pnpm-volume/72a24911-4d49-4ea5-aa93-31d2f107df86/node_modules/.registry.npmjs.org/ws/7.2.1/node_modules/ws/lib/receiver.js:423:14)
    at Receiver.getData (/rbd/pnpm-volume/72a24911-4d49-4ea5-aa93-31d2f107df86/node_modules/.registry.npmjs.org/ws/7.2.1/node_modules/ws/lib/receiver.js:353:17)
```

**Comment by Charsy89** [comment] 2020-01-17 02:45
I've identified the issue and it's only on wolfy's version because he edited it to use x-forwarded-for because glitch.me is weird (close this issue please)

**Comment by Charsy89** [comment] 2020-01-17 03:03
or no wait aaaaaaaaaa
why it reference room.join if it's complaining about line 59 in client.js (join hasn't even been executed yet)?!?!?

**Comment by BopItFreak** [comment] 2020-04-07 21:55
Usually this error is caused by the database getting messed up. I have to frequently delete users.json due to it being corrupted. Not sure why this happens.

**Closed** 2020-04-07 21:55 UTC
